openapi: 3.1.0
info:
  title: "catand API"
  description: "Catand API which handles nothing"
  version: "0.0.1"
tags:
  - name: "test"
    description: "Test"

paths:
  /api/test:
    get:
      summary: "Test"
      description: "Test"
      operationId: doTest
      tags:
        - "test"
      responses:
        "200":
          description: "The bets for the specified users and games"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Test"
        "500":
          description: "Internal server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          enum:
            - "TECHNICAL_ERROR"
            - "VALIDATION_ERROR"
        params:
          type: array
          items:
            type: string
      required:
        - code
    Test:
        type: object
        properties:
            test:
              type: string
        required:
          - test