linters:
  enable-all: true
  disable:
    - execinquery # deprecated
    - exportloopref # deprecated
    - canonicalheader
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forcetypeassert
    - gci
    - gocognit
    - godot
    - gofumpt
    - gomnd
    - interfacebloat
    - intrange
    - ireturn
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - nolintlint
    - nonamedreturns
    - perfsprint
    - revive
    - tagliatelle
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    # Should be enabled:
    - rowserrcheck
    - sqlclosecheck
    - nilnil
    - containedctx

linters-settings:
  lll:
    line-length: 200

  funlen:
    lines: 100
    statements: 50

  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    local-prefixes: catand

  govet:
    enable-all: true

  misspell:
    ignore-words:
      - catand

  unparam:
    check-exported: true

issues:
  # don't skip warning about doc comments
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Ignore fieldalignment
    - linters: [ govet ]
      text: "fieldalignment: struct with (.*) pointer bytes could be (.*)"
    # Ignore fieldalignment
    - linters: [ govet ]
      text: "fieldalignment: struct of size (.*) could be (.*)"
    # Ignore some comment rule
    - linters: [ stylecheck ]
      text: "ST1000: at least one file in a package should have a package comment"
    # Don't warn of potential file inclusion (dynamic file paths)
    - linters: [ gosec ]
      text: "Potential file inclusion via variable"
    - linters: [ gosec ]
      text: "Implicit memory aliasing in for loop"
    - linters: [ gosec ]
      text: "G115: integer overflow conversion"
    # Ignore some rules for tests files
    - path: _test\.go
      linters:
        - funlen
        - gosec
        - gosimple
        - govet
        - ineffassign
        - paralleltest
        - testifylint
        - testpackage
        - unparam
        - wastedassign
        - dupl

output:
  sort-results: true
